services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/root/data
    environment:
      - ENV=production
      - PORT=3000
      - LOG_LEVEL=info
      - DB_PATH=/root/data/daily-notes.db
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URL=postmessage
      - CORS_ORIGINS=${CORS_ORIGINS:-https://dailynotes.dev,https://www.dailynotes.dev}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
